kind: pipeline
type: docker
name: default

steps:
- name: unit-test
  image: golang
  volumes:
  - name: cache
    path: /go
  commands:
  - go mod download
  - go test -coverprofile=coverage.out -covermode=count ./...
  - go tool cover -html=coverage.out -o coverage.html
  - go tool cover -func=coverage.out | grep total

- name: race-test
  image: golang
  volumes:
  - name: cache
    path: /go
  commands:
  - go mod download
  - go test -race -short ./...

    #- name: build
    #  image: golang
    #  volumes:
    #  - name: cache
    #    path: /go
    #  commands:
    #  - go mod download
    #  - go build

volumes:
- name: cache
  temp: {}
